### ISSUE TITLE
Integration with dotansimha/graphql-code-generator

### ISSUE THREAD

**Issue by davetapley** [dillonkearns/elm-typescript-interop#20]
Disclaimer: This is purely speculative.

I've been playing with [{GraphQL} Code Generator](https://graphql-code-generator.com/) ([Github](https://github.com/dotansimha/graphql-code-generator)) for a React project, and noticed they have a [plugin](https://graphql-code-generator.com/docs/custom-codegen/write-your-plugin) framework, including a [ReasonML client](https://graphql-code-generator.com/docs/plugins/reason-client).

I don't know enough about elm-typescript-interop to know if [making it a plug in](https://graphql-code-generator.com/docs/custom-codegen/write-your-plugin) would be feasible? 🤔

**Comment by dillonkearns** [comment]
Hello! I'm having trouble understanding what problem this would solve. Could you clarify by describing a use case where this would provide value and walk me through how it would be used?

**Comment by dillonkearns** [comment]
Also, the link to "making it a plugin" seems to be a `graphql-code-generator.com` plugin. Maybe you meant to open this issue on `elm-graphql`...? Or maybe I'm missing something. How would `elm-typescript-interop` be used as a `graphql-code-generator.com` plugin?

**Comment by davetapley** [comment]
> Could you clarify by describing a use case where this would provide value and walk me through how it would be used?

Sure!

a. More exposure for Elm 😎 
b. I suppose it might be convenient if someone already using that code generator could just 'add a plugin' and get Elm code out too.

> How would elm-typescript-interop be used as a `graphql-code-generator` plugin?

I was hoping you could answer that 😂 
I know `elm-typescript-interop` has an NPM package which does the work of generating the Elm code, right? If so I _presume_ it'd be possible to right an interface between that and `graphql-code-generator`? 🤔

**Comment by dillonkearns** [comment]
> I know elm-typescript-interop has an NPM package which does the work of generating the Elm code, right? If so I presume it'd be possible to right an interface between that and graphql-code-generator? 🤔

It sounds like you're thinking of [`elm-graphql`](https://github.com/dillonkearns/elm-graphql). `elm-typescript-interop` doesn't generate Elm code. It generates a TypeScript type definition file. So this project is not related to GraphQL at all. Am I understanding right, or am I missing something?

**Comment by davetapley** [comment]
@dillonkearns oh, yep, my bad!
