### ISSUE TITLE
Parcel: Hangs and creates elm-package.json in 0.19 project

### ISSUE THREAD

**Issue by kodeFant** [dillonkearns/elm-typescript-interop#22]
Hi Dillon!

It seems like this package creates some confusion for Parcel using Elm 0.19. 

It correctly generates the index.d.ts file, but also creates an elm-package.json file in my src-folder that seems to confuse Parcel.

Parcel hangs and never generates the app.

Removing this package fixes the problem instantly, and I get the types just like they are supposed to be, so it has some practicality as long as I am willing to add and remove this package after each use 😊

**Comment by kodeFant** [comment]
Using it with npx instead of installing it as a local dependency seems to solve the problem, and it works just fine for my need.

**Comment by dillonkearns** [comment]
Thanks for the update! I'm glad it's working well now.
