### ISSUE TITLE
Support 0.19.1

### ISSUE THREAD

**Issue by kodeFant** [dillonkearns/elm-typescript-interop#24]
The script seems to complain upon using Elm 0.19.1, but I am guessing the implementation otherwise could be unchanged as it is fully backwards compatible?

**Comment by davidtoska** [comment]
Same issue here.

**Comment by holandes22** [comment]
+1 for this. @dillonkearns any chance the PR #23 is approved please?

**Comment by dillonkearns** [comment]
Let me know if you're still having issues here after merging the PR. Thank you! 🙏
