### ISSUE TITLE
Unable to install with npm (win64)

### ISSUE THREAD

**Issue by 124C41p** [dillonkearns/elm-typescript-interop#41]
My attempt to install with npm (npm i -D elm-typescript-interop) failed with error message "Downloading Elm binaries from https://dl.bintray.com/elmlang/elm-platform/0.18.0/win32-x64.tar.gz Error decompressing win32-x64.tar.gz Error: incorrect header check".

Seems the link is broken.

**Comment by dillonkearns** [comment]
Hello @124C41p, it looks like this issue with the previous Elm 0.18 binary host no longer being available: https://discourse.elm-lang.org/t/psa-old-elm-binary-downloads-now-gone/7319.

I haven't officially marked this package (`elm-typescript-interop`) as deprecated yet, but `elm-ts-interop` is now the new approach to this problem: https://npmjs.com/package/elm-ts-interop. I'll be officially marking this package as deprecated once I get some improved documentation for the free community edition of `elm-ts-interop`.

The pro version is at http://elm-ts-interop.com/ and you can see a walkthrough video of it here https://www.youtube.com/watch?v=FzCRbI4Ne6w and a podcast episode about it at https://elm-radio.com/episode/elm-ts-interop.

I would recommend using `elm-ts-interop` if possible. If you're not able to use `elm-ts-interop`, I'm not sure if there is a workaround, but I would be open to a pull request to point to a fixed Elm 0.18 NPM dependency (if there is one?).

**Comment by muelli** [comment]
Yeah, it has been fixed: https://discourse.elm-lang.org/t/psa-old-elm-binary-downloads-now-gone/7319/12

You want to pull `latest-0.18.0`.

**Comment by 124C41p** [comment]
That's perfect. Thanks a lot! :)

**Comment by dillonkearns** [comment]
Thanks for that @muelli. So sounds like this works without any changes to the package, which is great.

To clarify the steps for anyone else who may stumble upon this issue, I guess you just remove your local package-lock.json to allow it to resolve to the new elm 0.18 NPM dependency? Is that correct?
