### ISSUE TITLE
Does this work with Elm 0.19?

### ISSUE THREAD

**Issue by sporto** [dillonkearns/elm-typescript-interop#8]
Hi
I tried to use this, but hit an issue immediately. 
Is this meant to work with Elm 0.19?
Thanks

**Comment by dillonkearns** [comment]
Hey @sporto, that's correct it doesn't generate proper Typescript definitions for the generated Elm 0.19 format yet. It will be a pretty small change, I expect to have a fix out early next week once I'm back from my vacation.

I'll update this thread as soon as that's done. Thanks!

**Comment by dillonkearns** [comment]
And for reference, you can see my current todo list for this project here, it's generally pretty up-to-date. I may add a link to it in the Readme so others can see the road map: https://trello.com/b/WSvVUwaM/elm-typescript-interop

**Comment by dillonkearns** [comment]
Hello @sporto, `elm-typescript-interop` now works for Elm 0.19! Here's [the changelog entry](https://github.com/dillonkearns/elm-typescript-interop/blob/master/CHANGELOG.md#006---2018-09-12). I've also made several improvements, so you can now just run `elm-typescript-interop` from the directory with your `elm.json` file (or `elm-package.json`), and it will automatically generate everything for you in the right places for TypeScript imports to work. No need to specify output directories!

I'd love to hear your feedback once you try it out!
